/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package network.balanced.score.tokens;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class BoostedBalnTest {

    @Test
    void appHasAGreeting() {
        BoostedBaln classUnderTest = new BoostedBaln();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
