/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package network.balanced.score.tokens;

public class BoostedBaln {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new BoostedBaln().getGreeting());
    }
}
